### ISSUE TITLE
periodum.com bağlantısı About bölümüne eklensin

### ISSUE THREAD

**Issue by ozgurg** [evrimagaci/periodum#11]
Merhaba.

README.md'de veya GitHub'ın About bölümünde periodum.com'a giden bir bağlantı yok.
About bölümüne eklenmesi güzel olur.

![Screen Shot 2022-01-16 at 16 05 41](https://user-images.githubusercontent.com/6717356/149661156-00938795-07f2-4bb0-a537-2ab4d1c60549.jpg)

**Comment by ozgurg** [comment]
@cagrimertbakirci GitHub'ın kendisi doğrudan bağlantı eklememize izin veriyor. Açıklamaya yazmanıza gerek yok. Şu şekilde yapabilirsiniz:

https://user-images.githubusercontent.com/6717356/149682859-a97a346a-89b8-4b9b-a4fc-7b739f209d58.mp4

**Comment by cagrimertbakirci** [comment]
@ozgurg Tamamdır, ben oradaki placeholder'ı değiştirilemez link sanmışım. Şimdi hallettim, teşekkürler.
