### ISSUE TITLE
Chromium Element Mass Number Bug

### ISSUE THREAD

**Issue by fehmiisener** [evrimagaci/periodum#17]
When you move the isotope bar for the element chromium, the mass number is incorrectly displayed like this. "22 }}"
![image](https://user-images.githubusercontent.com/58306766/149677912-2339fb0f-093f-4540-a840-2d11faaf0d08.png)

**Comment by cagrimertbakirci** [comment]
@HKskn Bu sorun çözüldü mü acaba? Merge ettiysek kapatabilir miyiz?

**Comment by fehmiisener** [comment]
When I checked this on web site, it seems to be resolved.
