### ISSUE TITLE
Proje Koordinatörü/Koordinatörleri Belirleme

### ISSUE THREAD

**Issue by cagrimertbakirci** [evrimagaci/periodum#2]
Projeyi tamamen açık kaynak olarak sürdürmek istiyor olsak da, komüniteye liderlik edebilecek, Github ve Vue.js konusunda deneyimli kişilere ihtiyacımız var.

Eğer normalden birazcık daha fazla sorumluluk alabileceğinizi ve projeyi ilerletme konusunda aktif liderlikte bulunabileceğinizi düşünüyorsanız, burada bir veya birkaç kişi belirleyebiliriz.

**Tahmini Sorumluluklar:**

1. Github kuralları & koordinasyonu (örneğin GitHub'da İngilizce mi çalışmak daha iyi olur, bu tür detaylar belirlenecek)
2. Projenin gidişatı konusunda bizim (önceki aylarda) çizdiğimiz çerçeveyi şekillendirme ve gerçekleştirme
3. Proje akışına yardımcı olma ve yönlendirme.

İhtiyaca göre daha fazla kişi alabilir veya rolleri gözden geçirebiliriz.

**Comment by mehmetb** [comment]
Bence @bulentv komüniteye liderlik edebilir.

**Comment by fehmiisener** [comment]
Benim düşüncem GitHub gibi global bir platformu İngilizce kullanmak en faydalası olacağı. Hem tüm dünya genelinde bir proje olması daha kolay olur hem de open-source dediğimiz kavramı tam anlamı ile kavranır. Bu hedef doğrultusunda commit mesajları, issue topicleri vb. her şeyin İngilizce devam edilmesi lazım.

**Comment by fehmiisener** [comment]
Ayrıca bunu yazdığım yer doğru yer mi ve halihazırda kullanıyor musunuz bilmiyorum fakat CI/CD süreçleri de geliştirme ve yayınlama süreçlerini oldukça hızlandırabilir.
