### ISSUE TITLE
Tarayıcı Kontrolü

### ISSUE THREAD

**Issue by cagrimertbakirci** [evrimagaci/periodum#3]
Projenin farklı tarayıcılarda nasıl çalıştığını kontrol etmemiz ve aksaklıkları gidermemiz gerekiyor. 

En öncelikli olanlar:

1. Chrome (Temelde buna yönelik tasarlandı)
2. Firefox
3. Safari

Ek olarak:

1. Opera
2. Edge

Mobil tarayıcılar için ayrı issue oluşturacağız.

**Comment by evilese** [comment]
Tasarımsal bir şey belirtmek istiyorum. Hakkımızda sayfasında yazı maalesef okunabilirlik açısından iyi değil, ufak biz düzenleme yaptım belki işinize yarar.
----

/* LİNKLERİ DAHA OKUNABİLİR YAPAR */

.description>p>a {
    color: #75e8e6;
    text-decoration: none;
    font-weight: 700;
}

/* GENELİ DAHA OKUNABİLİR YAPAR */

.description[data-v-7fdfdd16] {
    font-size: 0.9em;
    color: #b5bac5;
    font-weight: 400;
    line-height: normal;
}

----

/* MEVCUT HALİ */
![1](https://user-images.githubusercontent.com/60050361/149655091-becf98b1-9e73-4286-92d0-10e6b29c8bec.PNG)

/* DÜZENLENEN HALİ */
![2](https://user-images.githubusercontent.com/60050361/149655105-6b01d90c-4a3e-4256-bb6f-87fb8917e3e5.PNG)

----

/* SCSS VERSİYON */ 

.description {
	>p {
		>a {
			color: #75e8e6;
			text-decoration: none;
			font-weight: 700;
		}
	}
	font-size: 0.9em;
	color: #b5bac5;
	font-weight: 400;
	line-height: normal;
}

**Comment by krumdahr** [comment]
Merhaba,
Firefox'da (96.0.1 (64 bit)) deyalı bilgi paneli transparan açıldığı için okumak pek mümkün değil maalesef.

![Screenshot 2022-01-16 at 17-43-25 periodium](https://user-images.githubusercontent.com/76871330/149664888-cf033fa0-2773-4c32-868e-91f6608cc640.png)

**Comment by erdemildiz** [comment]
Fontların daha okunabilir olması iyi olur.

**Comment by turkerdev** [comment]
> Merhaba, Firefox'da (96.0.1 (64 bit)) deyalı bilgi paneli transparan açıldığı için okumak pek mümkün değil maalesef.
> 
> ![Screenshot 2022-01-16 at 17-43-25 periodium](https://user-images.githubusercontent.com/76871330/149664888-cf033fa0-2773-4c32-868e-91f6608cc640.png)

Sıvı ile gazın resimleri ters olmuş sanırım.

**Comment by krumdahr** [comment]
Benzer transparan görünüm sorunu bileşik oluşturma panelinde de mevcut. Ayrıca ilk elenement (burada Al) koyu bir renk ile yazıldığı için okumayı güçleştiriyor.

![Screenshot 2022-01-18 at 10-26-34 periodium](https://user-images.githubusercontent.com/76871330/149890604-0cdaa7bb-3930-477c-ad8b-03e2b7dbb5e1.png)

**Comment by might4** [comment]
@cagrimertbakirci bence bu başlığı da tartışmaya atmak mantıklı olabilir

**Comment by nesimtunc** [comment]
Yukarida testlere ek olarak **Mac OS Monterey** ve **Windows 11** isletim sistemlerindeki **Safari**, **Edge** ve **Opera** ile denedim. Denemeyi base olarak Anasayfayi ele aldim. Diger alt sayfalardaki gorsel degisiklikler hemen hemen her yerde ayni ve kismen duzeltildi, duzeltiliyor.

**Cozunurluk:** 1920x910
**Test Ortami:** BrowserStack.com
**Sonuc:** Window 11 - Safari v5.1 haric basarili

Windows 11 Safari v5.1 Ekran Goruntuleri:

<img width="2032" alt="Screen Shot 2022-01-29 at 13 54 33" src="https://user-images.githubusercontent.com/680806/151647899-478cb214-8a7a-4e43-806d-b451b9d51f52.png">

<img width="2032" alt="Screen Shot 2022-01-29 at 13 54 48" src="https://user-images.githubusercontent.com/680806/151647898-abe6787e-0984-400b-bd54-92f8172609f2.png">

**Comment by nesimtunc** [comment]
Selam @evilese, degisikliklerin guzel gozukuyor, acaba onlari bir kod degisikligi olarak bize gondersen şık olmaz mı? 😎

**Comment by cagrimertbakirci** [comment]
> ```css
> /* LİNKLERİ DAHA OKUNABİLİR YAPAR */
> .description>p>a {
>     color: #75e8e6;
>     text-decoration: none;
>     font-weight: 700;
> }
> 
> /* GENELİ DAHA OKUNABİLİR YAPAR */
> 
> .description[data-v-7fdfdd16] {
>     font-size: 0.9em;
>     color: #b5bac5;
>     font-weight: 400;
>     line-height: normal;
> }
> ```

Buna bir PR şart. 😍
