### ISSUE TITLE
firefox tabanlı tarayıcılarda bileşik paneli yok

### ISSUE THREAD

**Issue by mehmet00000** [evrimagaci/periodum#36]
Firefox 96.0.1'de gördüğüm kadarıyla sağdaki bileşik paneli yok ancak Edge 97'de sorunsuz çalışıyor

**Comment by krumdahr** [comment]
Firefox 96.0.1'de sorunsuz çalışıyor bende

![Screenshot 2022-01-18 at 21-29-16 periodium](https://user-images.githubusercontent.com/76871330/149997288-58108786-e099-4e79-8c36-42b47061b236.png)
.

**Comment by Lucifer25x** [comment]
> Firefox 96.0.1'de gördüğüm kadarıyla sağdaki bileşik paneli yok ancak Edge 97'de sorunsuz çalışıyor

Ben de Firefox kullanıyorum, ama bende söylediğiniz tarz sorun yok. Siteyi yeniden ziyaret etmeyi deneyin, belki sorun sizinle ilgili bir şeydedir.

**Comment by cagrimertbakirci** [comment]
Bu gelip-giden bir hata sanıyorum. #18 altında çözmek üzereyiz, Firefox'ta da düzelecek diye ümit ediyorum. Takipte olun lütfen dostlar.

**Comment by mehmet00000** [comment]
@might4 galiba kullandığım eklentilerle ilgili değil çünkü şu an aynı eklentilerle manjaro'da denedim ve sorunsuz çalıştı.
![resim](https://user-images.githubusercontent.com/80150352/150535707-45f5256d-270d-4d23-854a-5d87054dd081.png)
eklentiler:
![resim](https://user-images.githubusercontent.com/80150352/150536198-7678d8bb-6fe1-41d1-a508-bd77895be138.png)

**Comment by HKskn** [comment]
@mehmet00000 incognito mode'da bir screen recording paylaşabilir misin?

**Comment by mehmet00000** [comment]
@HKskn  
incognitoda sorunsuz çalışıyor ama normalde de şuan sorunsuz çalışıyor

https://user-images.githubusercontent.com/80150352/150639646-ce2f9635-52e2-4702-adce-66d9a8df6587.mp4

**Comment by HKskn** [comment]
@mehmet00000  öyleyse browser cacheden dolayı eski versiyonu görüyordun. Bunla alakalı #18 le birlikte bir fix göndermiştik. Başka bir sorun yoksa issue'u kapatabiliriz.

**Comment by mehmet00000** [comment]
Herkese ilgisi için teşekkürler issue'u kapatıyorum
