### ISSUE TITLE
"Detaylı Bilgi" Kısmında Satır Araları Açılacak

### ISSUE THREAD

**Issue by cagrimertbakirci** [evrimagaci/periodum#8]
Şu anda siteden gelen yazıların okunurluğu biraz düşük, paragraf araları açılmalı, biraz okuma kolaylaştırıcı format düzenlemeleri yapılmalı.

![image](https://user-images.githubusercontent.com/9502185/149650208-233be936-3bc3-4e94-9c62-54632d0628c2.png)

**Comment by evilese** [comment]
/* Hatanın çözümü için gereken CSS 

.dialog-body > p > h2 {
    margin-bottom: 15px;
    margin-top: 15px;
    line-height: 45px;
}
.dialog-body {
    padding: 30px;
    position: relative;
    font-size: 16px;
}
.dialog-body > p {
    line-height: 19px;
}

*/

-----------

/* Scroll için daha estetik bir görüntü için CSS

::-webkit-scrollbar-thumb {
    width: 10px;
    background: #653eb9;
    border-radius: 10px;
}

::-webkit-scrollbar {
    width: 10px;
}

*/

![Ekran Alıntısı](https://user-images.githubusercontent.com/60050361/149654570-714a6af6-d7e5-4c34-b8ec-9164c9ac4b0d.PNG)

------------------

SCSS versiyon;

.dialog-body {
	>p {
		>h2 {
			margin-bottom: 15px;
			margin-top: 15px;
			line-height: 45px;
		}
		line-height: 19px;
	}
	padding: 30px;
	position: relative;
	font-size: 16px;
}
&::-webkit-scrollbar-thumb {
	width: 10px;
	background: #653eb9;
	border-radius: 10px;
}
&::-webkit-scrollbar {
	width: 10px;
}
