### ISSUE TITLE
Sidebar blur effect won't work on Mozilla Firefox.

### ISSUE THREAD

**Issue by Tahckn** [evrimagaci/periodum#83]
Expected Result :  Screenshot on Microsoft Edge 

![Edge](https://user-images.githubusercontent.com/77683100/157898555-434bf5c8-58d9-4955-997c-ad241b78bed7.png)

Actual Result : Screenshot on Mozilla Firefox 
![Mozilla](https://user-images.githubusercontent.com/77683100/157898601-363b4458-1afe-49cd-b1b5-557accac687d.png)

Priority Level : Low

**Comment by nesimtunc** [comment]
Thanks for reporting it, this issue already has been fixed in #55 and merged but haven't published on production, yet.

It's a good practice to search in the issues before creating one.
